import type { Template } from '@/types'
import { PLANNER_TYPE_PAGES, DEFAULT_CONFIG } from './defaults'

export const TEMPLATES: Template[] = [
  {
    id: 'tpl_daily_minimal',
    name: 'Minimal Daily',
    type: 'daily',
    description: 'Clean hourly schedule with priority blocks. Perfect for focused daily planning.',
    thumbnail: '',
    category: 'Daily',
    tags: ['minimal', 'clean', 'productivity'],
    pages: PLANNER_TYPE_PAGES.daily(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#111827', accentColor: '#D6CFC7' },
    isFavorite: false,
    isPremium: false,
    downloads: 2847,
  },
  {
    id: 'tpl_daily_sage',
    name: 'Sage Daily',
    type: 'daily',
    description: 'Nature-inspired daily planner in calming sage tones.',
    thumbnail: '',
    category: 'Daily',
    tags: ['sage', 'nature', 'calm'],
    pages: PLANNER_TYPE_PAGES.daily(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#2D4A22', accentColor: '#C8D5B9' },
    isFavorite: false,
    isPremium: false,
    downloads: 1932,
  },
  {
    id: 'tpl_weekly_classic',
    name: 'Classic Weekly',
    type: 'weekly',
    description: 'Timeless weekly layout with full day columns and goal tracking.',
    thumbnail: '',
    category: 'Weekly',
    tags: ['classic', 'structured', 'weekly'],
    pages: PLANNER_TYPE_PAGES.weekly(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#111827', accentColor: '#D6CFC7' },
    isFavorite: false,
    isPremium: false,
    downloads: 3541,
  },
  {
    id: 'tpl_monthly_calendar',
    name: 'Monthly Calendar',
    type: 'monthly',
    description: 'Full-page monthly calendar with goals and notes sidebar.',
    thumbnail: '',
    category: 'Monthly',
    tags: ['calendar', 'monthly', 'overview'],
    pages: PLANNER_TYPE_PAGES.monthly(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#0C2340', accentColor: '#B8D4E8' },
    isFavorite: false,
    isPremium: false,
    downloads: 4218,
  },
  {
    id: 'tpl_habit_tracker',
    name: 'Habit Grid',
    type: 'habit',
    description: 'Track up to 12 habits with a visual monthly grid and progress insights.',
    thumbnail: '',
    category: 'Tracker',
    tags: ['habits', 'tracker', 'grid', 'streak'],
    pages: PLANNER_TYPE_PAGES.habit(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#2D1B69', accentColor: '#D4C5F9' },
    isFavorite: false,
    isPremium: true,
    downloads: 5102,
  },
  {
    id: 'tpl_budget_planner',
    name: 'Budget Master',
    type: 'budget',
    description: 'Complete monthly budget with income, fixed/variable expenses and savings tracker.',
    thumbnail: '',
    category: 'Finance',
    tags: ['budget', 'finance', 'money', 'savings'],
    pages: PLANNER_TYPE_PAGES.budget(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#1A2E1A', accentColor: '#B9D4BC' },
    isFavorite: false,
    isPremium: false,
    downloads: 6304,
  },
  {
    id: 'tpl_wellness_tracker',
    name: 'Wellness Daily',
    type: 'wellness',
    description: 'Holistic daily wellness tracking — mood, water, sleep, meals, and gratitude.',
    thumbnail: '',
    category: 'Wellness',
    tags: ['wellness', 'health', 'mood', 'self-care'],
    pages: PLANNER_TYPE_PAGES.wellness(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#4A1942', accentColor: '#F2C4CE' },
    isFavorite: false,
    isPremium: false,
    downloads: 3987,
  },
  {
    id: 'tpl_fitness_log',
    name: 'Workout Log',
    type: 'fitness',
    description: 'Log exercises, sets, reps, and personal records with a clean athletic layout.',
    thumbnail: '',
    category: 'Fitness',
    tags: ['fitness', 'workout', 'gym', 'exercise'],
    pages: PLANNER_TYPE_PAGES.fitness(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#0D0D0D', accentColor: '#BFBFBF' },
    isFavorite: false,
    isPremium: false,
    downloads: 2671,
  },
  {
    id: 'tpl_student_planner',
    name: 'Student Success',
    type: 'student',
    description: 'Academic daily planner with class schedule, assignment tracker and study goals.',
    thumbnail: '',
    category: 'Academic',
    tags: ['student', 'school', 'academic', 'study'],
    pages: PLANNER_TYPE_PAGES.student(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#3D1A08', accentColor: '#F2C49B' },
    isFavorite: false,
    isPremium: false,
    downloads: 4856,
  },
  {
    id: 'tpl_business_pro',
    name: 'Business Pro',
    type: 'business',
    description: 'Professional daily planner with priority matrix, project tracking, and EOD review.',
    thumbnail: '',
    category: 'Business',
    tags: ['business', 'professional', 'projects', 'productivity'],
    pages: PLANNER_TYPE_PAGES.business(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#111827', accentColor: '#D6CFC7' },
    isFavorite: false,
    isPremium: true,
    downloads: 7231,
  },
  {
    id: 'tpl_weekly_blush',
    name: 'Blush Weekly',
    type: 'weekly',
    description: 'Elegant weekly planner in soft blush and mauve tones.',
    thumbnail: '',
    category: 'Weekly',
    tags: ['blush', 'feminine', 'elegant'],
    pages: PLANNER_TYPE_PAGES.weekly(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#4A1942', accentColor: '#F2C4CE' },
    isFavorite: false,
    isPremium: true,
    downloads: 2198,
  },
  {
    id: 'tpl_daily_business',
    name: 'Executive Daily',
    type: 'daily',
    description: 'Power planner for executives with meeting prep and EOD review sections.',
    thumbnail: '',
    category: 'Business',
    tags: ['executive', 'professional', 'leadership'],
    pages: PLANNER_TYPE_PAGES.daily(),
    config: { ...DEFAULT_CONFIG, primaryColor: '#0C2340', accentColor: '#B8D4E8' },
    isFavorite: false,
    isPremium: true,
    downloads: 3104,
  },
]

export const TEMPLATE_CATEGORIES = [
  'All',
  'Daily',
  'Weekly',
  'Monthly',
  'Tracker',
  'Finance',
  'Wellness',
  'Fitness',
  'Academic',
  'Business',
]
