import type { Template } from '@/types'
import { PLANNER_TYPE_PAGES, DEFAULT_CONFIG, makeBlock, makePage } from './defaults'

const cfg = (overrides: object) => ({ ...DEFAULT_CONFIG, ...overrides })

export const TEMPLATES: Template[] = [
  // ── DAILY ──────────────────────────────────────────────────────────────────
  { id:'tpl_daily_minimal', name:'Minimal Daily', type:'daily', description:'Clean, structured daily planner with time blocks and reflection.', thumbnail:'', category:'Daily', tags:['minimal','clean','productivity'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, isTrending:true, downloads:4821, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },
  { id:'tpl_daily_sage', name:'Sage Daily', type:'daily', description:'Nature-inspired daily planner in calming sage and forest tones.', thumbnail:'', category:'Daily', tags:['sage','nature','calm'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:2941, accentHue:'150', themeId:'cottagecore', config:cfg({ primaryColor:'#1A3A2A', secondaryColor:'#52796F', accentColor:'#CAD2C5' }) },
  { id:'tpl_daily_executive', name:'Executive Daily', type:'daily', description:'Power planner for executives — priority matrix, meetings, and EOD review.', thumbnail:'', category:'Daily', tags:['executive','business','leadership'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:true, isBestseller:true, downloads:3204, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#0C2340', accentColor:'#B8D4E8' }) },
  { id:'tpl_daily_rose', name:'Rose Daily', type:'daily', description:'Elegant daily planner in rose and blush for a warm, personal feel.', thumbnail:'', category:'Daily', tags:['rose','elegant','feminine'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:1872, accentHue:'345', themeId:'floral', config:cfg({ primaryColor:'#4A1942', secondaryColor:'#9D174D', accentColor:'#FBCFE8' }) },
  { id:'tpl_daily_ink', name:'Ink Daily', type:'daily', description:'Bold monochrome daily planner with strong typographic hierarchy.', thumbnail:'', category:'Daily', tags:['bold','monochrome','minimal'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:1540, accentHue:'0', themeId:'minimalist', config:cfg({ primaryColor:'#0D0D0D', secondaryColor:'#404040', accentColor:'#D4D4D4' }) },
  { id:'tpl_daily_boho', name:'Boho Daily', type:'daily', description:'Earthy boho daily planner with warm amber and natural tones.', thumbnail:'', category:'Daily', tags:['boho','earthy','warm'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:2100, accentHue:'35', themeId:'boho', config:cfg({ primaryColor:'#5C4033', accentColor:'#D4A26A' }) },
  { id:'tpl_daily_adhd', name:'ADHD Daily', type:'adhd', description:'Brain-friendly daily planner with clear visual cues and minimal overwhelm.', thumbnail:'', category:'ADHD', tags:['adhd','focus','brain-friendly'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:true, isBestseller:true, downloads:4560, accentHue:'290', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },
  { id:'tpl_daily_timeblock', name:'Time Blocking Pro', type:'daily', description:'Complete time blocking planner for peak productivity sessions.', thumbnail:'', category:'Daily', tags:['time-blocking','productivity','focus'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:true, isTrending:true, downloads:3890, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },

  // ── WEEKLY ─────────────────────────────────────────────────────────────────
  { id:'tpl_weekly_classic', name:'Classic Weekly', type:'weekly', description:'Timeless 7-day column layout with goal tracking and notes.', thumbnail:'', category:'Weekly', tags:['classic','structured','weekly'], pages:PLANNER_TYPE_PAGES.weekly(), isFavorite:false, isPremium:false, isBestseller:true, downloads:5241, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },
  { id:'tpl_weekly_blush', name:'Blush Weekly', type:'weekly', description:'Soft blush and dusty pink weekly planner with elegant styling.', thumbnail:'', category:'Weekly', tags:['blush','feminine','elegant'], pages:PLANNER_TYPE_PAGES.weekly(), isFavorite:false, isPremium:true, downloads:2198, accentHue:'345', themeId:'floral', config:cfg({ primaryColor:'#4A1942', accentColor:'#F5D0CA' }) },
  { id:'tpl_weekly_indigo', name:'Indigo Weekly', type:'weekly', description:'Vibrant indigo weekly planner with bold section headers.', thumbnail:'', category:'Weekly', tags:['indigo','bold','colorful'], pages:PLANNER_TYPE_PAGES.weekly(), isFavorite:false, isPremium:false, downloads:1784, accentHue:'245', themeId:'pastelDreams', config:cfg({ primaryColor:'#1E1B4B', secondaryColor:'#4338CA', accentColor:'#C7D2FE' }) },
  { id:'tpl_weekly_academic', name:'Academic Weekly', type:'student', description:'Student-focused weekly planner with class schedule and assignments.', thumbnail:'', category:'Student', tags:['academic','student','weekly'], pages:PLANNER_TYPE_PAGES.weekly(), isFavorite:false, isPremium:false, downloads:3200, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#BBDEFB' }) },
  { id:'tpl_weekly_boho', name:'Boho Weekly', type:'weekly', description:'Earthy boho weekly view with natural botanical accents.', thumbnail:'', category:'Weekly', tags:['boho','nature','weekly'], pages:PLANNER_TYPE_PAGES.weekly(), isFavorite:false, isPremium:false, downloads:1650, accentHue:'35', themeId:'boho', config:cfg({ primaryColor:'#5C4033', accentColor:'#D4A26A' }) },

  // ── MONTHLY ────────────────────────────────────────────────────────────────
  { id:'tpl_monthly_classic', name:'Monthly Overview', type:'monthly', description:'Full calendar page with monthly goals and habit tracker.', thumbnail:'', category:'Monthly', tags:['calendar','monthly','overview'], pages:PLANNER_TYPE_PAGES.monthly(), isFavorite:false, isPremium:false, isBestseller:true, downloads:6102, accentHue:'215', themeId:'minimalist', config:cfg({ primaryColor:'#0C2340', accentColor:'#B8D4E8' }) },
  { id:'tpl_monthly_gold', name:'Gold Monthly', type:'monthly', description:'Warm gold and amber monthly calendar with rich typographic style.', thumbnail:'', category:'Monthly', tags:['gold','warm','premium'], pages:PLANNER_TYPE_PAGES.monthly(), isFavorite:false, isPremium:true, downloads:2341, accentHue:'43', themeId:'royal', config:cfg({ primaryColor:'#3D1A08', secondaryColor:'#A07840', accentColor:'#E8D5B4' }) },
  { id:'tpl_monthly_nature', name:'Nature Monthly', type:'monthly', description:'Fresh green monthly calendar with nature-inspired accents.', thumbnail:'', category:'Monthly', tags:['nature','green','monthly'], pages:PLANNER_TYPE_PAGES.monthly(), isFavorite:false, isPremium:false, downloads:1890, accentHue:'150', themeId:'nature', config:cfg({ primaryColor:'#1B4332', accentColor:'#52B788' }) },
  { id:'tpl_monthly_goal', name:'Goal Monthly', type:'monthly', description:'Monthly goal setting with 90-day vision and progress tracking.', thumbnail:'', category:'Monthly', tags:['goals','planning','monthly'], pages:PLANNER_TYPE_PAGES.monthly(), isFavorite:false, isPremium:true, isTrending:true, downloads:4120, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },

  // ── HABIT ──────────────────────────────────────────────────────────────────
  { id:'tpl_habit_grid', name:'Habit Grid', type:'habit', description:'Classic 31-day habit tracking grid with monthly overview.', thumbnail:'', category:'Wellness', tags:['habits','tracking','monthly'], pages:PLANNER_TYPE_PAGES.habit(), isFavorite:false, isPremium:false, isBestseller:true, downloads:8901, accentHue:'270', themeId:'nature', config:cfg({ primaryColor:'#1B4332', accentColor:'#52B788' }) },
  { id:'tpl_habit_wellness', name:'Wellness Habits', type:'habit', description:'Holistic habit tracker with wellness, fitness, and mindset categories.', thumbnail:'', category:'Wellness', tags:['wellness','habits','holistic'], pages:PLANNER_TYPE_PAGES.habit(), isFavorite:false, isPremium:true, downloads:3450, accentHue:'330', themeId:'pastelDreams', config:cfg({ primaryColor:'#6A1B9A', accentColor:'#CE93D8' }) },
  { id:'tpl_habit_minimal', name:'Minimal Habits', type:'habit', description:'Clean, no-fuss habit tracker for serious practitioners.', thumbnail:'', category:'Wellness', tags:['minimal','habits','clean'], pages:PLANNER_TYPE_PAGES.habit(), isFavorite:false, isPremium:false, downloads:2890, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },

  // ── BUDGET / FINANCE ───────────────────────────────────────────────────────
  { id:'tpl_budget_master', name:'Budget Master', type:'budget', description:'Complete monthly budget planner with income, expenses, and savings.', thumbnail:'', category:'Finance', tags:['budget','finance','monthly'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:false, isBestseller:true, downloads:5891, accentHue:'150', themeId:'nature', config:cfg({ primaryColor:'#1B4332', accentColor:'#52B788' }) },
  { id:'tpl_budget_minimalist', name:'Budget Minimalist', type:'budget', description:'Simple, clean budget tracker for no-fuss money management.', thumbnail:'', category:'Finance', tags:['budget','minimal','clean'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:false, downloads:3120, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },
  { id:'tpl_budget_savings52', name:'52-Week Savings', type:'finance', description:'52-week savings challenge with visual progress tracker.', thumbnail:'', category:'Finance', tags:['savings','challenge','52-week'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:false, isTrending:true, isBestseller:true, downloads:7823, accentHue:'150', themeId:'nature', config:cfg({ primaryColor:'#1B4332', accentColor:'#74C69D' }) },
  { id:'tpl_budget_debtsnow', name:'Debt Snowball', type:'finance', description:'Systematic debt payoff tracker with snowball method.', thumbnail:'', category:'Finance', tags:['debt','snowball','finance'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:true, downloads:3450, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },
  { id:'tpl_budget_bills', name:'Bill Tracker', type:'finance', description:'Monthly bill payment organizer with checkboxes and due dates.', thumbnail:'', category:'Finance', tags:['bills','tracker','payments'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:false, downloads:3901, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#334155' }) },
  { id:'tpl_budget_nospend', name:'No-Spend Challenge', type:'finance', description:'30-day no-spend challenge tracker with daily check-ins.', thumbnail:'', category:'Finance', tags:['no-spend','challenge','savings'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:false, downloads:2890, accentHue:'150', themeId:'cottagecore', config:cfg({ primaryColor:'#33691E', accentColor:'#8BC34A' }) },
  { id:'tpl_budget_sinking', name:'Sinking Funds', type:'finance', description:'Multiple sinking fund tracker for planned irregular expenses.', thumbnail:'', category:'Finance', tags:['sinking-funds','savings','planning'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:true, downloads:2341, accentHue:'43', themeId:'royal', config:cfg({ primaryColor:'#1A237E', accentColor:'#C9A227' }) },

  // ── WELLNESS ────────────────────────────────────────────────────────────────
  { id:'tpl_wellness_daily', name:'Wellness Daily', type:'wellness', description:'Holistic daily wellness planner for mind, body, and spirit.', thumbnail:'', category:'Wellness', tags:['wellness','holistic','daily'], pages:PLANNER_TYPE_PAGES.wellness(), isFavorite:false, isPremium:true, downloads:3450, accentHue:'330', themeId:'floral', config:cfg({ primaryColor:'#6B2737', accentColor:'#F06292' }) },
  { id:'tpl_wellness_gratitude', name:'Gratitude Journal', type:'journal', description:'Daily gratitude practice with deep reflection prompts.', thumbnail:'', category:'Wellness', tags:['gratitude','journal','mindfulness'], pages:PLANNER_TYPE_PAGES.wellness(), isFavorite:false, isPremium:false, isBestseller:true, downloads:6780, accentHue:'330', themeId:'floral', config:cfg({ primaryColor:'#6B2737', accentColor:'#F06292' }) },
  { id:'tpl_wellness_mood', name:'Mood Journal', type:'wellness', description:'Daily mood tracking with reflection and pattern insights.', thumbnail:'', category:'Wellness', tags:['mood','journal','mental-health'], pages:PLANNER_TYPE_PAGES.wellness(), isFavorite:false, isPremium:false, isTrending:true, downloads:4320, accentHue:'270', themeId:'pastelDreams', config:cfg({ primaryColor:'#6A1B9A', accentColor:'#CE93D8' }) },
  { id:'tpl_wellness_selfcare', name:'Self-Care Planner', type:'wellness', description:'Comprehensive self-care system with weekly rituals and goals.', thumbnail:'', category:'Wellness', tags:['self-care','wellness','rituals'], pages:PLANNER_TYPE_PAGES.wellness(), isFavorite:false, isPremium:true, downloads:3120, accentHue:'330', themeId:'valentine', config:cfg({ primaryColor:'#880E4F', accentColor:'#FF4081' }) },
  { id:'tpl_wellness_therapy', name:'Therapy Journal', type:'journal', description:'Structured journal for therapy prep, session notes, and insights.', thumbnail:'', category:'Wellness', tags:['therapy','journal','mental-health'], pages:PLANNER_TYPE_PAGES.wellness(), isFavorite:false, isPremium:true, downloads:2980, accentHue:'270', themeId:'pastelDreams', config:cfg({ primaryColor:'#6A1B9A', accentColor:'#CE93D8' }) },

  // ── FITNESS ─────────────────────────────────────────────────────────────────
  { id:'tpl_fitness_log', name:'Workout Log', type:'fitness', description:'Comprehensive workout logging with sets, reps, and progress tracking.', thumbnail:'', category:'Fitness', tags:['workout','fitness','log'], pages:PLANNER_TYPE_PAGES.fitness(), isFavorite:false, isPremium:false, isBestseller:true, downloads:5670, accentHue:'0', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },
  { id:'tpl_fitness_meal', name:'Meal Planner', type:'fitness', description:'Weekly meal planning with nutrition notes and grocery list.', thumbnail:'', category:'Fitness', tags:['meal','nutrition','weekly'], pages:PLANNER_TYPE_PAGES.fitness(), isFavorite:false, isPremium:false, isBestseller:true, downloads:7234, accentHue:'90', themeId:'cottagecore', config:cfg({ primaryColor:'#33691E', accentColor:'#8BC34A' }) },
  { id:'tpl_fitness_weight', name:'Weight Tracker', type:'fitness', description:'Weekly weigh-in tracker with goal visualization.', thumbnail:'', category:'Fitness', tags:['weight','tracker','fitness'], pages:PLANNER_TYPE_PAGES.fitness(), isFavorite:false, isPremium:false, downloads:4890, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },
  { id:'tpl_fitness_water', name:'Water Tracker', type:'fitness', description:'Daily hydration tracking with 8-glass goal system.', thumbnail:'', category:'Fitness', tags:['water','hydration','health'], pages:PLANNER_TYPE_PAGES.fitness(), isFavorite:false, isPremium:false, downloads:3456, accentHue:'200', themeId:'tropical', config:cfg({ primaryColor:'#004D40', accentColor:'#FFD54F' }) },

  // ── STUDENT ─────────────────────────────────────────────────────────────────
  { id:'tpl_student_success', name:'Study Success', type:'student', description:'Complete student planner with assignments, exams, and study sessions.', thumbnail:'', category:'Student', tags:['student','study','academic'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:false, isBestseller:true, downloads:6780, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },
  { id:'tpl_student_cornell', name:'Cornell Notes', type:'student', description:'Classic Cornell note-taking system for structured learning.', thumbnail:'', category:'Student', tags:['notes','cornell','study'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:false, isBestseller:true, downloads:8901, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },
  { id:'tpl_student_exam', name:'Exam Revision', type:'student', description:'Structured exam revision planner with countdown and topic tracker.', thumbnail:'', category:'Student', tags:['exam','revision','study'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:true, isTrending:true, downloads:4230, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },
  { id:'tpl_student_semester', name:'Semester Planner', type:'student', description:'Full semester overview with monthly breakdowns and deadlines.', thumbnail:'', category:'Student', tags:['semester','academic','planning'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:true, downloads:4120, accentHue:'210', themeId:'darkAcademia', config:cfg({ primaryColor:'#2C1810', accentColor:'#8D6E63' }) },
  { id:'tpl_student_reading', name:'Reading Log', type:'student', description:'Book reading tracker with notes, quotes, and ratings.', thumbnail:'', category:'Student', tags:['reading','books','tracker'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:false, downloads:3456, accentHue:'210', themeId:'darkAcademia', config:cfg({ primaryColor:'#2C1810', accentColor:'#8D6E63' }) },

  // ── TEACHER ─────────────────────────────────────────────────────────────────
  { id:'tpl_teacher_lesson', name:'Lesson Planner', type:'teacher', description:'Weekly lesson planning with objectives, activities, and assessment.', thumbnail:'', category:'Teacher', tags:['teacher','lesson','classroom'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:true, isBestseller:true, downloads:4560, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },
  { id:'tpl_teacher_gradebook', name:'Grade Book', type:'teacher', description:'Student grade tracking and management with averages.', thumbnail:'', category:'Teacher', tags:['grades','teacher','tracking'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:true, downloads:3210, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },
  { id:'tpl_teacher_classroom', name:'Classroom Planner', type:'teacher', description:'Complete classroom organization planner for the academic year.', thumbnail:'', category:'Teacher', tags:['classroom','teacher','organize'], pages:PLANNER_TYPE_PAGES.student(), isFavorite:false, isPremium:true, downloads:2890, accentHue:'150', themeId:'cottagecore', config:cfg({ primaryColor:'#33691E', accentColor:'#8BC34A' }) },

  // ── BUSINESS ───────────────────────────────────────────────────────────────
  { id:'tpl_business_pro', name:'Business Pro', type:'business', description:'Executive business planner with KPIs, meetings, and project tracking.', thumbnail:'', category:'Business', tags:['business','executive','kpi'], pages:PLANNER_TYPE_PAGES.business(), isFavorite:false, isPremium:true, isBestseller:true, downloads:5670, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#334155' }) },
  { id:'tpl_business_content', name:'Content Planner', type:'business', description:'90-day content marketing calendar with platform strategy.', thumbnail:'', category:'Business', tags:['content','marketing','social'], pages:PLANNER_TYPE_PAGES.business(), isFavorite:false, isPremium:true, isTrending:true, downloads:5670, accentHue:'270', themeId:'pastelDreams', config:cfg({ primaryColor:'#6A1B9A', accentColor:'#CE93D8' }) },
  { id:'tpl_business_social', name:'Social Media Planner', type:'business', description:'Cross-platform social media content calendar and analytics.', thumbnail:'', category:'Business', tags:['social-media','content','marketing'], pages:PLANNER_TYPE_PAGES.business(), isFavorite:false, isPremium:true, downloads:4890, accentHue:'215', themeId:'productivity', config:cfg({ primaryColor:'#1565C0', accentColor:'#2196F3' }) },
  { id:'tpl_business_freelance', name:'Freelance Tracker', type:'business', description:'Client management, invoicing, and project tracking for freelancers.', thumbnail:'', category:'Business', tags:['freelance','clients','invoicing'], pages:PLANNER_TYPE_PAGES.business(), isFavorite:false, isPremium:true, downloads:3890, accentHue:'43', themeId:'royal', config:cfg({ primaryColor:'#1A237E', accentColor:'#C9A227' }) },
  { id:'tpl_business_meetings', name:'Meeting Notes', type:'business', description:'Professional meeting notes template with agenda and action items.', thumbnail:'', category:'Business', tags:['meetings','notes','actions'], pages:PLANNER_TYPE_PAGES.business(), isFavorite:false, isPremium:false, downloads:4120, accentHue:'220', themeId:'minimalist', config:cfg({ primaryColor:'#0F172A', accentColor:'#E2E8F0' }) },

  // ── KIDS ────────────────────────────────────────────────────────────────────
  { id:'tpl_kids_chore', name:'Chore Chart', type:'kids', description:'Fun and colorful weekly chore chart with reward system.', thumbnail:'', category:'Kids', tags:['kids','chores','rewards'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, isBestseller:true, downloads:5670, accentHue:'330', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },
  { id:'tpl_kids_reward', name:'Reward Chart', type:'kids', description:'Star reward chart for kids with weekly tracking.', thumbnail:'', category:'Kids', tags:['kids','rewards','stars'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, isBestseller:true, downloads:6780, accentHue:'330', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },
  { id:'tpl_kids_reading', name:'Kids Reading Log', type:'kids', description:'Colorful reading log designed for young readers.', thumbnail:'', category:'Kids', tags:['kids','reading','books'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:4321, accentHue:'200', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },
  { id:'tpl_kids_routine', name:'Daily Routine', type:'kids', description:'Morning and evening routine chart with pictures and times.', thumbnail:'', category:'Kids', tags:['kids','routine','daily'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:3890, accentHue:'200', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },

  // ── WEDDING ─────────────────────────────────────────────────────────────────
  { id:'tpl_wedding_master', name:'Wedding Planner', type:'wedding', description:'Complete wedding day planning system from engagement to honeymoon.', thumbnail:'', category:'Wedding', tags:['wedding','planning','bride'], pages:PLANNER_TYPE_PAGES.monthly(), isFavorite:false, isPremium:true, isBestseller:true, downloads:8901, accentHue:'330', themeId:'floral', config:cfg({ primaryColor:'#6B2737', accentColor:'#F06292' }) },
  { id:'tpl_wedding_budget', name:'Wedding Budget', type:'wedding', description:'Comprehensive wedding budget tracker by category with vendors.', thumbnail:'', category:'Wedding', tags:['wedding','budget','vendors'], pages:PLANNER_TYPE_PAGES.budget(), isFavorite:false, isPremium:true, downloads:4560, accentHue:'43', themeId:'royal', config:cfg({ primaryColor:'#1A237E', accentColor:'#C9A227' }) },
  { id:'tpl_wedding_guests', name:'Guest List Manager', type:'wedding', description:'RSVP tracking, seating chart, and meal preference management.', thumbnail:'', category:'Wedding', tags:['wedding','guests','rsvp'], pages:PLANNER_TYPE_PAGES.monthly(), isFavorite:false, isPremium:false, downloads:5670, accentHue:'330', themeId:'floral', config:cfg({ primaryColor:'#6B2737', accentColor:'#F06292' }) },
  { id:'tpl_wedding_vendors', name:'Vendor Tracker', type:'wedding', description:'Vendor contacts, contracts, payments, and timeline.', thumbnail:'', category:'Wedding', tags:['wedding','vendors','contracts'], pages:PLANNER_TYPE_PAGES.monthly(), isFavorite:false, isPremium:true, downloads:3450, accentHue:'330', themeId:'floral', config:cfg({ primaryColor:'#6B2737', accentColor:'#F06292' }) },

  // ── JOURNALS ────────────────────────────────────────────────────────────────
  { id:'tpl_journal_morning', name:'Morning Pages', type:'journal', description:'Free-flow morning journaling for clarity and creativity.', thumbnail:'', category:'Journal', tags:['morning','journal','writing'], pages:PLANNER_TYPE_PAGES.journal(), isFavorite:false, isPremium:false, downloads:4560, accentHue:'35', themeId:'boho', config:cfg({ primaryColor:'#5C4033', accentColor:'#D4A26A' }) },
  { id:'tpl_journal_5year', name:'5-Year Journal', type:'journal', description:'One-line-per-day journal for five years of reflections.', thumbnail:'', category:'Journal', tags:['journal','5-year','reflection'], pages:PLANNER_TYPE_PAGES.journal(), isFavorite:false, isPremium:true, downloads:3210, accentHue:'210', themeId:'darkAcademia', config:cfg({ primaryColor:'#2C1810', accentColor:'#8D6E63' }) },
  { id:'tpl_journal_manifestation', name:'Manifestation Journal', type:'journal', description:'Law of attraction journaling with affirmations and vision work.', thumbnail:'', category:'Journal', tags:['manifestation','law-of-attraction','affirmations'], pages:PLANNER_TYPE_PAGES.journal(), isFavorite:false, isPremium:true, isTrending:true, downloads:7890, accentHue:'270', themeId:'galaxy', config:cfg({ primaryColor:'#E8D5FF', accentColor:'#7C4DFF' }) },
  { id:'tpl_journal_travel', name:'Travel Journal', type:'journal', description:'Document your adventures with maps, memories, and mementos.', thumbnail:'', category:'Journal', tags:['travel','adventure','memories'], pages:PLANNER_TYPE_PAGES.journal(), isFavorite:false, isPremium:true, downloads:5670, accentHue:'200', themeId:'tropical', config:cfg({ primaryColor:'#004D40', accentColor:'#FFD54F' }) },
  { id:'tpl_journal_pregnancy', name:'Pregnancy Journal', type:'journal', description:'Week-by-week pregnancy journey with milestones and memories.', thumbnail:'', category:'Journal', tags:['pregnancy','baby','journal'], pages:PLANNER_TYPE_PAGES.journal(), isFavorite:false, isPremium:true, downloads:4560, accentHue:'330', themeId:'pastelDreams', config:cfg({ primaryColor:'#6A1B9A', accentColor:'#CE93D8' }) },
  { id:'tpl_journal_recipe', name:'Recipe Journal', type:'journal', description:'Personal recipe collection with notes and memory prompts.', thumbnail:'', category:'Journal', tags:['recipes','food','journal'], pages:PLANNER_TYPE_PAGES.journal(), isFavorite:false, isPremium:false, downloads:3456, accentHue:'35', themeId:'cottagecore', config:cfg({ primaryColor:'#33691E', accentColor:'#8BC34A' }) },

  // ── ADHD ────────────────────────────────────────────────────────────────────
  { id:'tpl_adhd_brain', name:'ADHD Brain Dump', type:'adhd', description:'Structured brain dump for ADHD minds with capture and sort system.', thumbnail:'', category:'ADHD', tags:['adhd','brain-dump','capture'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:3210, accentHue:'290', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },
  { id:'tpl_adhd_routine', name:'ADHD Routine Tracker', type:'adhd', description:'Visual morning and evening routine builder for ADHD brains.', thumbnail:'', category:'ADHD', tags:['adhd','routine','visual'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:2890, accentHue:'290', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },
  { id:'tpl_adhd_reward', name:'ADHD Reward System', type:'adhd', description:'Gamified reward system for completing daily tasks and habits.', thumbnail:'', category:'ADHD', tags:['adhd','rewards','gamification'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:false, downloads:1980, accentHue:'290', themeId:'kawaii', config:cfg({ primaryColor:'#AD1457', accentColor:'#FF80AB' }) },
  { id:'tpl_adhd_eisenhower', name:'ADHD Focus Matrix', type:'adhd', description:'Eisenhower matrix adapted for ADHD task prioritization.', thumbnail:'', category:'ADHD', tags:['adhd','focus','priority'], pages:PLANNER_TYPE_PAGES.daily(), isFavorite:false, isPremium:true, isTrending:true, downloads:2450, accentHue:'270', themeId:'pastelDreams', config:cfg({ primaryColor:'#6A1B9A', accentColor:'#CE93D8' }) },

  // ── CREATIVE ────────────────────────────────────────────────────────────────
  { id:'tpl_creative_content', name:'Content Creator', type:'creative', description:'Social media content calendar for creators and influencers.', thumbnail:'', category:'Business', tags:['creator','content','social'], pages:PLANNER_TYPE_PAGES.business(), isFavorite:false, isPremium:true, isTrending:true, downloads:5670, accentHue:'270', themeId:'pastelDreams', config:cfg({ primaryColor:'#6A1B9A', accentColor:'#CE93D8' }) },
  { id:'tpl_creative_design', name:'Design Sprint', type:'creative', description:'Weekly design sprint planning with client briefs and deliverables.', thumbnail:'', category:'Business', tags:['design','sprint','creative'], pages:PLANNER_TYPE_PAGES.business(), isFavorite:false, isPremium:true, downloads:2341, accentHue:'200', themeId:'tropical', config:cfg({ primaryColor:'#004D40', accentColor:'#FFD54F' }) },
]

export const TEMPLATE_CATEGORIES = [...new Set(TEMPLATES.map(t => t.category))].sort()
